"""Phase 6 — NeMo Agent Toolkit (NAT) self-verify loop.

This phase sits *between* stages conceptually: the runner emits
``retry_queue.jsonl`` (rows with actionable repair hints), and a NAT
ReAct agent reads that queue and tries to repair each row via stage-
1/2/3 tools until it's valid or ``max_iter`` is reached.

Implementation notes
--------------------
- Built on ``nat.agent.react_agent.agent.ReActAgentGraph`` — NAT's
  LangGraph-backed ReAct impl. The agent prompt is generated by NAT's
  own ``create_react_agent_prompt``. NAT's ReAct uses prompt-parse
  dispatch (``Action:`` / ``Action Input:``), so the LLM does not need
  native tool-calling support.
- LLM: ``langchain_openai.ChatOpenAI`` pointed at NIM's
  ``integrate.api.nvidia.com/v1`` endpoint, serving
  ``nvidia/nemotron-3-super-120b-a12b`` (same judge model, different
  role). API key from ``NEMO_3_SUPER``. We use ``ChatOpenAI`` instead of
  ``ChatNVIDIA`` because the NV wrapper has a duplicate-catalog bug for
  this specific model (``Multiple candidates ... in available_models``);
  the NIM chat endpoint is OpenAI-wire-compatible, so ChatOpenAI is a
  drop-in.
- Tools: LangChain ``@tool`` functions. ``revalidate`` is the only one
  that is self-contained inside stage 3; stage-1 / stage-2 repair tools
  are adapters that the orchestrator wires in through
  :class:`StageCallables` when the corresponding stage packages are
  available. Missing stages raise ``NotImplementedError`` and the agent
  treats that as a failed tool call (NAT catches + passes back).

``run_self_verify(row, ...)`` is the public entrypoint and is never
invoked by ``runner.run_async`` — the orchestrator (or a separate
script) drives it over the retry queue.
"""

from __future__ import annotations

import json
import os
from collections.abc import Awaitable, Callable
from dataclasses import dataclass
from typing import Any

from nemos_dream.schemas import Stage3Output

_AGENT_LLM_MODEL = "nvidia/nemotron-3-super-120b-a12b"
_AGENT_LLM_KEY_ENV = "NEMO_3_SUPER"


@dataclass
class StageCallables:
    """Repair-tool adapter bundle wired by the orchestrator.

    Each callable takes a single :class:`Stage3Output` and returns a
    (possibly repaired) copy. When a stage isn't implemented yet,
    provide a stub that raises :class:`NotImplementedError`; the ReAct
    agent catches the exception and picks another tool.
    """

    stage1_redecompose: Callable[[Stage3Output], Awaitable[Stage3Output]]
    maps_ref_redo: Callable[[Stage3Output], Awaitable[Stage3Output]]
    stage2_rewrite: Callable[[Stage3Output], Awaitable[Stage3Output]]
    websearch_cultural: Callable[[Stage3Output], Awaitable[Stage3Output]]
    revalidate: Callable[[Stage3Output], Awaitable[Stage3Output]]


_TOOL_DESCRIPTIONS = {
    "stage1_redecompose": (
        "Re-run stage-1 dialogue decomposition on the EN source. Use when "
        "turn_count_parity, turn_index_order, or speech-acts look wrong."
    ),
    "maps_ref_redo": (
        "Re-resolve mapped_refs via dict → retriever → web+llm chain. "
        "Use when cultural_ref_coverage, mapped_ref_ko_hangul, or "
        "mapped_ref_type_consistency fails."
    ),
    "stage2_rewrite": (
        "Regenerate the Korean rewrite with adjusted persona/register. "
        "Use when register_consistency, persona_style_consistency, "
        "naturalness, or property_preservation is low."
    ),
    "websearch_cultural": (
        "Fetch fresh cultural-ref evidence via web search. Use alongside "
        "maps_ref_redo when the dict + retriever path still fails."
    ),
    "revalidate": (
        "Re-run stage-3 phases 1-5 on the (possibly repaired) row. The "
        "agent MUST call this after each repair to check whether the row "
        "now passes."
    ),
}


def _row_input_str(row: Stage3Output) -> str:
    return json.dumps(
        {
            "id": row.id,
            "reject_reasons": [rr.model_dump() for rr in row.reject_reasons],
            "retry_actions": [a.model_dump() for a in row.retry_actions],
            "quality": row.quality.model_dump(),
        },
        ensure_ascii=False,
    )


def _build_tools(stages: StageCallables, enabled_actions: list[str], *, state: dict[str, Any]):
    """Build LangChain BaseTools that close over the mutable ``state``.

    The agent uses string IO, so we keep the actual :class:`Stage3Output`
    in ``state["row"]`` and have each tool read/mutate that. This matches
    NAT's ReAct framework (it wraps sync/async LangChain tools).
    """
    from langchain_core.tools import StructuredTool  # noqa: PLC0415 — lazy LC import

    registry = {
        "stage1_redecompose": stages.stage1_redecompose,
        "maps_ref_redo": stages.maps_ref_redo,
        "stage2_rewrite": stages.stage2_rewrite,
        "websearch_cultural": stages.websearch_cultural,
        "revalidate": stages.revalidate,
    }

    def _make_tool(name: str, fn: Callable[[Stage3Output], Awaitable[Stage3Output]]):
        async def _coro(_: str = "") -> str:
            try:
                state["row"] = await fn(state["row"])
            except NotImplementedError as exc:
                return f"tool_unavailable: {exc}"
            row = state["row"]
            return json.dumps(
                {
                    "valid": row.valid,
                    "reject_reasons": [rr.rule for rr in row.reject_reasons],
                    "quality_aggregate": row.quality.aggregate,
                },
                ensure_ascii=False,
            )

        return StructuredTool.from_function(
            coroutine=_coro,
            name=name,
            description=_TOOL_DESCRIPTIONS[name],
        )

    tools = []
    # revalidate is always enabled — the agent needs a way to check
    # progress after each repair.
    for name in enabled_actions + (["revalidate"] if "revalidate" not in enabled_actions else []):
        fn = registry.get(name)
        if fn is None:
            continue
        tools.append(_make_tool(name, fn))
    return tools


async def run_self_verify(
    row: Stage3Output,
    *,
    stages: StageCallables,
    enabled_actions: list[str],
    max_iter: int = 2,
    llm_model: str = _AGENT_LLM_MODEL,
) -> Stage3Output:
    """Run the NAT ReAct loop on one row up to ``max_iter`` times.

    Returns the (possibly now-valid) row. Raises at runtime when
    ``nvidia-nat`` / ``langchain-nvidia-ai-endpoints`` are not installed.
    """
    from langchain_core.messages import HumanMessage  # noqa: PLC0415
    from langchain_openai import ChatOpenAI  # noqa: PLC0415
    from nat.agent.react_agent.agent import (  # noqa: PLC0415
        ReActAgentGraph,
        ReActGraphState,
        create_react_agent_prompt,
    )
    from nat.agent.react_agent.register import ReActAgentWorkflowConfig  # noqa: PLC0415

    api_key = os.environ.get(_AGENT_LLM_KEY_ENV) or os.environ.get("NVIDIA_API_KEY")
    if not api_key:
        raise RuntimeError(
            f"{_AGENT_LLM_KEY_ENV} (or NVIDIA_API_KEY) must be set for the NAT self-verify agent."
        )

    llm = ChatOpenAI(
        model=llm_model,
        api_key=api_key,
        base_url="https://integrate.api.nvidia.com/v1",
        temperature=0.0,
    )

    cfg = ReActAgentWorkflowConfig(
        llm_name="stage3_self_verify",
        tool_names=list(enabled_actions) + ["revalidate"],
        max_tool_calls=max(1, max_iter) * (len(enabled_actions) + 1),
        verbose=False,
    )
    prompt = create_react_agent_prompt(cfg)

    state_ctx: dict[str, Any] = {"row": row}
    tools = _build_tools(stages, enabled_actions=enabled_actions, state=state_ctx)

    agent = ReActAgentGraph(llm=llm, prompt=prompt, tools=tools)
    graph = await agent.build_graph()

    user_prompt = (
        "A stage-3 dialogue row was rejected. Your goal: make it valid by calling "
        "the repair tools, then call `revalidate` to confirm. Stop as soon as "
        "`valid=true`. Row diagnostics follow.\n\n" + _row_input_str(row)
    )
    initial_state = ReActGraphState(messages=[HumanMessage(content=user_prompt)])
    await graph.ainvoke(initial_state)

    return state_ctx["row"]
